### ISSUE TITLE
上传操作：异常：Error：unable to verify the first certificate

### ISSUE THREAD

**Issue by AntonioDC-AAA** [zhanghuid/picgo-plugin-gitee#10]
由于网络原因本地离线安装picgo，发现上传操作：异常：Error：unable to verify the first certificate

**Comment by zhanghuid** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zhanghuid** [comment]
@AntonioDC-AAA 盲猜，会不会离线，上传不了（要上传到 gitee，需要联网）的问题呢？
