### ISSUE TITLE
不能上传图片

### ISSUE THREAD

**Issue by FulChou** [zhanghuid/picgo-plugin-gitee#4]
作者您好，按照您的配置之后，图片还是没有上传到gitee中

**Comment by zhanghuid** [comment]
@CSU-FulChou 贴一下你的配置

**Comment by FulChou** [comment]
> @CSU-FulChou 贴一下你的配置
我的配置是：

![image](https://user-images.githubusercontent.com/46887649/88003971-a0868900-cb38-11ea-871b-6413c0bc3726.png)

**Comment by zhanghuid** [comment]
@CSU-FulChou
如下图：**不需要owner的配置的**
![image](https://user-images.githubusercontent.com/12711819/88060303-a4e28e80-cb98-11ea-9862-641e6a70a525.png)

格式:
`https://gitee.com/api/v5/repos/{owner}/{repo}/contents/{path}`
具体可参考
> [gitee](https://gitee.com/api/v5/swagger#/postV5ReposOwnerRepoContentsPath)

**Comment by FulChou** [comment]
thank you&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "huid"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 晚上9:27
收件人: "zhanghuid/picgo-plugin-gitee"<picgo-plugin-gitee@noreply.github.com&gt;; 
抄送: "周福"<602933854@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [zhanghuid/picgo-plugin-gitee] 不能上传图片 (#4)





 
如下图：不需要owner的配置的
 
 
格式:
 https://gitee.com/api/v5/repos/{owner}/{repo}/contents/{path}
 具体可参考
  
gitee
