### ISSUE TITLE
文件名或路径包含中文时，删除无法同步到gitee

### ISSUE THREAD

**Issue by 570748428** [zhanghuid/picgo-plugin-gitee#7]
文件名或路径包含中文，在相册中删除图片，picgo反馈删除成功，但是在gitee上并没有被删除。

**Comment by zhanghuid** [comment]
emm.... 是目录没删除，还是文件没删除，还是都没删除？？

**Comment by zhanghuid** [comment]
@570748428  emmm.... 是目录没删除，还是文件没删除，还是都没删除？？

**Comment by 570748428** [comment]
> 
> 
> @570748428 emmm.... 是目录没删除，还是文件没删除，还是都没删除？？

都没删除

**Comment by zhanghuid** [comment]
@570748428 已处理，请更新插件
