### ISSUE TITLE
[bug]在相册选中多个文件删除，gitee上只能删除其中一个

### ISSUE THREAD

**Issue by 570748428** [zhanghuid/picgo-plugin-gitee#8]
[bug]在相册选中多个文件删除，gitee上只能删除其中一个，picgo.log中其他几个图片报“更新失败”，报错信息如下：
{"name":"StatusCodeError","statusCode":400,"message":"400 - \"{\\\"message\\\":\\\"更新失败\\\"}\"","error":"{\"message\":\"更新失败\"}","options":{"method":"DELETE","url":"……………………","headers":{"contentType":"application/json;charset=UTF-8","User-Agent":"PicGo"},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":400,"body":"{\"message\":\"更新失败\"}","headers":{"date":"Fri, 24 Sep 2021 02:51:59 GMT","content-type":"application/json","content-length":"26","connection":"close","server":"nginx","cache-control":"no-cache","x-request-id":"7761aa6fd3dc1205d02bf3a90a1c1216","x-runtime":"0.149083","vary":"Origin","x-frame-options":"SAMEORIGIN"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"gitee.com","port":443,"hostname":"gitee.com","hash":null,"search":"?access_token=……&message=null&sha=e9162b84029b295d90696be41ede7758fb5dd287","query":"access_token=……&message=null&sha=e9162b84029b295d90696be41ede7758fb5dd287","pathname":"/api/v5/repos/mclwork/picgo/contents/img/%E4%BA%8C/2.1.jpg","path":"/api/v5/repos/mclwork/picgo/contents/img/%E4%BA%8C/2.1.jpg?access_token=……&message=null&sha=e9162b84029b295d90696be41ede7758fb5dd287","href":"https://gitee.com/api/v5/repos/mclwork/picgo/contents/img/%E4%BA%8C/2.1.jpg?access_token=……&message=null&sha=e9162b84029b295d90696be41ede7758fb5dd287"},"method":"DELETE","headers":{"contentType":"application/json;charset=UTF-8","User-Agent":"PicGo","content-length":0}}}}

**Comment by zhanghuid** [comment]
@570748428 已解决，请升级到最新
