### ISSUE TITLE
请问如何同步原gitee仓库下的图片到picgo的相册中

### ISSUE THREAD

**Issue by convictss** [zhanghuid/picgo-plugin-gitee#9]
感谢作者开发的插件，如题，在更换电脑后重装了picgo与本上传插件，但是无法同步下远程仓库的图片信息到本地picgo的相册中，或者可能是我不知道同步的方法。。

**Comment by zhanghuid** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zhanghuid** [comment]
@convictss 这个应该是没有支持的，一键同步远程到本地，我先记得 todo list 里

**Comment by convictss** [comment]
OK, thanks
